"""Convert the SoS metadata spreadsheet to the committed YAML rules artifact.

This is a dev-time script that reads ``docs/sos-dataset/sos metadata.xlsx`` and
writes ``src/cit/resources/rules/sos_results_rules.yml``.  The CIT runtime consumes
that YAML file but never imports openpyxl; only this script does.

Usage::

    python tools/rules_convert.py
        --source '/path/to/docs/sos-dataset/sos metadata.xlsx'
        --output src/cit/resources/rules/sos_results_rules.yml
"""

import argparse
import math
from pathlib import Path

import openpyxl
import yaml

# ---------------------------------------------------------------------------
# Sheet names
# ---------------------------------------------------------------------------
_GLOBAL_ATTR_SHEET = "SoS Results Global Attributes"
_VARIABLE_SHEET = "SoS Results Variables"
_FILL_VALUES_SHEET = "Fill Values"

# ---------------------------------------------------------------------------
# Column indices — global-attributes sheet
# ---------------------------------------------------------------------------
_GA_REQUIRED_COL = 0
_GA_NAME_COL = 1

# ---------------------------------------------------------------------------
# Column indices — variables sheet
# ---------------------------------------------------------------------------
_VA_GROUP_COL = 0
_VA_VAR_COL = 2
_VA_LONG_NAME_COL = 3
_VA_COMMENT_COL = 4
_VA_UNITS_COL = 5
# col 6 is _FillValue — intentionally omitted from per-variable attrs
_VA_VALID_MIN_COL = 7
_VA_VALID_MAX_COL = 8
_VA_CCT_COL = 9

# Attribute key names aligned with the column order above (fill value excluded)
_VA_ATTR_KEYS = ("long_name", "comment", "units", "valid_min", "valid_max", "coverage_content_type")
_VA_ATTR_COLS = (
    _VA_LONG_NAME_COL,
    _VA_COMMENT_COL,
    _VA_UNITS_COL,
    _VA_VALID_MIN_COL,
    _VA_VALID_MAX_COL,
    _VA_CCT_COL,
)

# ---------------------------------------------------------------------------
# Column indices — fill-values sheet
# ---------------------------------------------------------------------------
_FV_TYPE_COL = 0
_FV_VALUE_COL = 1

# ---------------------------------------------------------------------------
# Fill-value canonicalisation
# ---------------------------------------------------------------------------
# openpyxl reads the Float fill value as -999999999999.0 (float precision).
# The canonical SoS value is -9.99999999999e+11, which is the same IEEE 754
# double but stored here for explicit, auditable conversion.
_FLOAT_FILL_CANONICAL: float = -9.99999999999e11
_FLOAT_FILL_FROM_XLSX: float = -999999999999.0

_FLOAT_TYPE_NAME = "Float"
_CHAR_TYPE_NAME = "Char"
_INT_TYPE_PREFIX = "Int"

# ---------------------------------------------------------------------------
# Default output path (relative to this script's repository root)
# ---------------------------------------------------------------------------
_DEFAULT_OUTPUT: Path = (
    Path(__file__).parent.parent / "src" / "cit" / "resources" / "rules" / "sos_results_rules.yml"
)

# ---------------------------------------------------------------------------
# Header prepended to the generated YAML file
# ---------------------------------------------------------------------------
_YAML_HEADER = (
    "# Auto-generated by tools/rules_convert.py from docs/sos-dataset/sos metadata.xlsx.\n"
    "# Do NOT hand-edit — re-run the converter to update.\n"
    "#\n"
)


def parse_global_attributes(wb: openpyxl.Workbook) -> list[str]:
    """Return the names of required global attributes from the spreadsheet.

    Reads the ``SoS Results Global Attributes`` sheet. The first row is a
    header and is skipped. Any subsequent row whose first column is ``True``
    contributes its attribute name (second column) to the result.

    Args:
        wb: An open openpyxl workbook (``read_only=True, data_only=True``).

    Returns:
        A list of 32 required global-attribute names, in sheet order.
    """
    ws = wb[_GLOBAL_ATTR_SHEET]
    rows = ws.iter_rows(values_only=True)
    next(rows)  # skip header row (col[0]=False, col[1]='Attribute Name')
    return [row[_GA_NAME_COL] for row in rows if row[_GA_REQUIRED_COL] is True]


def parse_variable_attributes(wb: openpyxl.Workbook) -> dict:
    """Return per-variable SoS attribute dicts grouped by module name.

    Reads the ``SoS Results Variables`` sheet. The first two rows (header and
    column-description row) are skipped. Rows where the variable name (column 2)
    or group name (column 0) is ``None`` are skipped. The ``_FillValue`` column
    is excluded from each variable's attribute dict; ``None`` values in any
    retained attribute are also omitted.

    Args:
        wb: An open openpyxl workbook (``read_only=True, data_only=True``).

    Returns:
        A nested dict of the form
        ``{group_name: {variable_name: {attr: value, ...}, ...}, ...}``
        covering 14 groups.
    """
    ws = wb[_VARIABLE_SHEET]
    rows = ws.iter_rows(values_only=True)
    next(rows)  # skip header
    next(rows)  # skip description row

    result: dict[str, dict[str, dict[str, object]]] = {}

    for row in rows:
        group: object = row[_VA_GROUP_COL]
        variable: object = row[_VA_VAR_COL]
        if variable is None or group is None:
            continue  # skip group-header rows and ungrouped variables

        attrs: dict[str, object] = {
            key: row[col]
            for key, col in zip(_VA_ATTR_KEYS, _VA_ATTR_COLS)
            if row[col] is not None
        }

        group_key = str(group)
        if group_key not in result:
            result[group_key] = {}
        result[group_key][str(variable)] = attrs

    return result


def parse_fill_values(wb: openpyxl.Workbook) -> dict:
    """Return the SoS fill-value table keyed by type name.

    Reads the ``Fill Values`` sheet. Rows where the type-name column is ``None``
    are skipped. Two special cases apply:

    - ``Float``: openpyxl returns ``-999999999999.0`` (float-precision artefact);
      it is replaced by the canonical ``-9.99999999999e+11``.
    - ``Char``: openpyxl returns ``'"x"'`` (with surrounding double-quotes);
      the quotes are stripped to yield ``'x'``.
    - ``Int``/``Int9``: whole-number floats (e.g. ``-999.0``) are cast to ``int``.

    Args:
        wb: An open openpyxl workbook (``read_only=True, data_only=True``).

    Returns:
        A dict mapping type name to fill value, e.g.
        ``{'Float': -999999999999.0, 'Int': -999, 'Int9': -99999999, 'Char': 'x'}``.
    """
    ws = wb[_FILL_VALUES_SHEET]
    result: dict[str, object] = {}

    rows = ws.iter_rows(values_only=True)
    next(rows)  # skip header row ('Variable Type', 'Fill Value', ...)

    for row in rows:
        type_name: object = row[_FV_TYPE_COL]
        value: object = row[_FV_VALUE_COL]

        if type_name is None:
            continue

        type_str = str(type_name)

        if type_str == _FLOAT_TYPE_NAME and isinstance(value, float):
            if math.isclose(value, _FLOAT_FILL_FROM_XLSX, rel_tol=1e-5):
                value = _FLOAT_FILL_CANONICAL

        elif type_str.startswith(_INT_TYPE_PREFIX) and isinstance(value, float) and value.is_integer():
            value = int(value)

        elif type_str == _CHAR_TYPE_NAME and isinstance(value, str):
            value = value.strip('"')

        result[type_str] = value

    return result


def main() -> None:
    """Parse the SoS metadata spreadsheet and write the YAML rules artifact."""
    parser = argparse.ArgumentParser(
        description="Convert docs/sos-dataset/sos metadata.xlsx to sos_results_rules.yml.",
    )
    parser.add_argument(
        "--source",
        required=True,
        metavar="PATH",
        help="Path to the SoS metadata spreadsheet (sos metadata.xlsx).",
    )
    parser.add_argument(
        "--output",
        default=str(_DEFAULT_OUTPUT),
        metavar="PATH",
        help=(
            "Destination path for the generated YAML file "
            f"(default: {_DEFAULT_OUTPUT})."
        ),
    )

    args = parser.parse_args()
    source = Path(args.source)
    output = Path(args.output)

    wb = openpyxl.load_workbook(source, read_only=True, data_only=True)

    data = {
        "global_attributes": parse_global_attributes(wb),
        "variable_attributes": parse_variable_attributes(wb),
        "fill_values": parse_fill_values(wb),
    }

    output.parent.mkdir(parents=True, exist_ok=True)
    yaml_str = yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)
    output.write_text(_YAML_HEADER + yaml_str, encoding="utf-8")

    print(f"Wrote {output}")  # noqa: T201


if __name__ == "__main__":
    main()
